[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
;board_build.core = earlephilhower
;board_build.core = arduino
;board_build.filesystem_size = 0.25m
framework = arduino

;board_build.f_cpu = 50000000L ;50Mhz
;board_build.f_cpu = 100000000L ;100Mhz
;board_build.f_cpu = 120000000L ;120Mhz
;board_build.f_cpu = 125000000L ;125Mhz (default)
;board_build.f_cpu = 133000000L ;133Mhz (default)
;board_build.f_cpu = 150000000L ;150Mhz (overclock)
;board_build.f_cpu = 175000000L ;175Mhz (overclock) (does not run)
;board_build.f_cpu = 200000000L ;200Mhz (overclock)
;board_build.f_cpu = 225000000L ;225Mhz (overclock)
;board_build.f_cpu = 240000000L ;240Mhz (overclock)
board_build.f_cpu = 250000000L ;250Mhz (overclock)
;board_build.f_cpu = 275000000L ;275Mhz (overclock) (does not run)
;board_build.f_cpu = 300000000L ;300Mhz (overclock) (does not run)

board_build.flash_mode = qio

monitor_filters = default, colorize

[env:pico]
board = rpipico
;board_build.filesystem = littlefs
build_flags =
	-D VID=0x2e8a
	-D PID=0x000a
  -D CFG_TUSB_CONFIG_FILE=\"tusb_config.h\"
	-D USE_TINYUSB
	-D USB_CONFIG_POWER=250
lib_deps =
	;adafruit/Adafruit NeoPixel@^1.10.5
	;sekigon-gonnoc/Pico PIO USB
	;adafruit/Adafruit InternalFlash@^0.1.0
  robtillaart/CRC @ ^1.0.2

lib_ignore = 
	;Adafruit NeoPixel
	;SdFat - Adafruit Fork
	;MIDI Library
	;Adafruit TinyUSB Library
