// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// shift_reg //
// --------- //

#define shift_reg_wrap_target 0
#define shift_reg_wrap 7

static const uint16_t shift_reg_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0     
    0xe200, //  1: set    pins, 0         side 0 [2] 
    0xe001, //  2: set    pins, 1         side 0     
    0xe027, //  3: set    x, 7            side 0     
    0x4001, //  4: in     pins, 1         side 0     
    0xb142, //  5: nop                    side 1 [1] 
    0x0344, //  6: jmp    x--, 4          side 0 [3] 
    0x8020, //  7: push   block           side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shift_reg_program = {
    .instructions = shift_reg_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config shift_reg_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shift_reg_wrap_target, offset + shift_reg_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

/*
 * input_pin should be ROM_READ, output_pin should be level shifter direction
 */
void shift_reg_program_init(PIO pio, uint sm, uint offset, uint clock_pin, uint q_pin)
{
  /* Q pin is the input */
  pio_gpio_init(pio, q_pin);
  pio_sm_set_consecutive_pindirs(pio, sm, q_pin, 1, false);
  /* Now the outputs, clock followed by SH/LD */
  uint sh_ld_pin = clock_pin+1;
  pio_gpio_init(pio, clock_pin);
  pio_gpio_init(pio, sh_ld_pin);
  pio_sm_set_consecutive_pindirs(pio, sm, clock_pin, 1, true); gpio_put( clock_pin, 0 );
  pio_sm_set_consecutive_pindirs(pio, sm, sh_ld_pin, 1, true); gpio_put( sh_ld_pin, 1 );
  /* Pick up config */
  pio_sm_config c = shift_reg_program_get_default_config(offset);
  /* Configure IN set, one pin, it's the Q pin */
  sm_config_set_in_pins(&c, q_pin);
  /* "in shift" is leftwards with auto push disabled (I do it manually after 8 bit reads) */
  sm_config_set_in_shift(&c, false, false, 8);
  /* Configure SET set, one pin, it's the shift/load pin */
  sm_config_set_set_pins(&c, sh_ld_pin, 1);
  /* Configure the side set pin, it's the clock pin */
  sm_config_set_sideset_pins(&c, clock_pin);
  /* Initialise the state machine, but don't start it yet */
  pio_sm_init(pio, sm, offset, &c);
  pio_sm_set_enabled(pio, sm, false);
}

#endif
